# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160810_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_1',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.CharField(default=0, max_length=10000, verbose_name='内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
