# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activatecode',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
