# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0002_auto_20160814_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activatecode',
            options={'verbose_name': '激活码', 'verbose_name_plural': '激活码'},
        ),
    ]
